import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});
export const metadata: Metadata = {
  title: "Vibely",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>

        <main className="bg-primary-50 w-full h-[100vh] overflow-hidden md:h-full p-2  md:p-12 relative  items-center flex">
          <section className=" w-[537px] mx-auto  border-4 border-main h-screen md:h-[955px] rounded-[40px] bg-white overflow-hidden">
            {children}
          </section>
        </main>
        <Toaster position="top-center" richColors />

      </body>
    </html>
  );
}
